### ISSUE TITLE
No numpy checklist

### ISSUE THREAD

**Issue by Thrameos** [Thrameos/jpype#42]
Attempt to deal with two (seemingly) mutually exclusive requests.  

1. Make JPype integrate with numpy better for better speed performance.
2. Make JPype not require numpy to operate.

**Comment by Thrameos** [comment]
- [x] JArray must inherit from PyJPArray
- [x] Remove numpy includes
- [x] JPArray::GetSlice will return JArray instance
- [x] JPArray::SetSlice must support sequence and memory view
- [x] PyJPArray must support memory view
- [x] Slice must replicate on Java call usage
- [x] Slice must replicate on copy ctor
- [x] Object arrays handle special
- [x] JPArray must have start, stop, step, 
- [x] Backport PyJPArray from 0.8
- [x] Rework getArrayRange
- [x] Rework setArrayRange
- [x] Clone on cast
- [x] Slice assignment must be safe from self assignment
- [x] Figure out how to extract data from struct API in C++
- [ ] Figure out how to get Python devs to respond regarding missing buffer API in the ABI
- [x] Incorporate type conversion table for setSlice from buffers to support numpy
- [x] Test getSlice against list with slices and compound slices
- [x] Test setSlice from buffers
- [x] Test getSlice to buffers 

https://docs.python.org/3/c-api/typeobj.html#buffer-structs
https://docs.python.org/3/library/struct.html#module-struct

**Comment by Thrameos** [comment]
@marscher One big challenge on this is trying to match which rules array set slice should use.  The closest equivalent I can find is

https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html

My best guess currently given the prior implementation is unsafe if sizes match otherwise no conversion as we dont appear to check the Python format codes.  It only checks itemsize.   This is mostly safe but does automatically turn floats to gibberish as a buggy side effect if you try to cast to int. 

If I have to redo it then it needs to make some sense while not blatently replicating useless bugs.  Java rules would require safe with same type (double to float) but they dont specify what to do with unsigned.  
Thus i am guessing safe with same type plus automatic unsigned to signed on same size would be the most compatible to our current implementation and still not allow insane conversions (double to short)

Bool and char is also weird edge cases.  The most permissive bool cases is anything that is not zero is true.  That would seem like Python valid syntax, but not Java safe.  Char has encoding requirements and like should not take buffer syntax at all.

Do you have any opinions on this?
