### ISSUE TITLE
Task list for JPype 0.8 Release

### ISSUE THREAD

**Issue by Thrameos** [Thrameos/jpype#44]
- [x] Get all pull requests pulled.
- [x] Finish the documentation.
- [x] Scan documentation for api issues that require action.
- [x] Scan issue list for api issues that require action.
- [x] Resolve api issues.
- [x] Remove deprecated code.
- [ ] Test.
- [ ] Check with stakeholders.

Looks like about two weeks of work.  Apply a factor of PI and we are on target for a June release.

**Comment by Thrameos** [comment]
Additional items for 0.8 release

- [x] Deal with JChar.  This is the only type remaining that has a bad return contract in which the type passed is not the type returned. (optional)
- [x] Finish extraction of javadoc so the stub generator can distribute documentation. (needed)
- [x] Deal with the release mechanism (tired of running into release issues) (required)
- [x] Deal with jaydebeapi.   We need a better solution than having people pin to an ancient version. (needed)
- [x] Fix broken read the docs
